name: Build

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: PlatformIO Run
          uses: karniv00l/platformio-run-action@v1
          with:
            silent: false
            verbose: true
            disable-auto-clean: false
